import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'


export async function getStaticProps() {
  const res = await fetch(`${process.env.API}/?limit=${40}`);

  const data = await res.json();

  data.results.forEach((item, index) => {
    item.id = index + 1;
  })

  return {
    props: {pokemons: data.results}
  }
}


export default function Home({ pokemons }) {
  return (
    <div>
      <Head>
        <title>PokeNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/favicon.ico" />
      </Head>
      <h1 className={styles.title}>
        <span>Poke</span>Next
        <Image 
          src="/images/pokeball.png" 
          width="50" height="50" 
          alt="ball">
        </Image>
      </h1>    

      <div className="container">
        <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
          {pokemons.map((pokemon) => (
            <div key={pokemon.id} className="col">
              <Card pokemon={pokemon}/>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
