import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../styles/Pokemon.module.css'

export const getStaticPaths = async() => {
  const res = await fetch(`${process.env.API}/?limit=${40}`);

  const data = await res.json();

  const paths = data.results.map((pokemon, index) => {
    return {
      params: {pokemonId: (index+1).toString()}
    }
  })

  return {
    paths,
    fallback: false
  }
  
}

export const getStaticProps = async(context) => {
  const id = context.params.pokemonId

  const res = await fetch(`${process.env.API}${id}`)

  const data = await res.json()

  return {
    props : {pokemon: data}
  }

}

export default function Pokemon({pokemon}) {
  return (
   <>
   <Head>
        <title>PokeNext - {pokemon.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/favicon.ico" />
    </Head>
    <div className="container my-5">
      <div className="pokemom d-flex flex-column align-items-center justify-content-center ">
        <h1 className='mb-5'>
          <span className='bg-dark text-white p-3 rounded fw-bold'>
            {pokemon.name}
          </span>
        </h1>

        <Image
          src={`https://cdn.traction.one/pokedex/pokemon/${pokemon.id}.png`}
          width="200"
          height="200"
          alt={pokemon.name}
          className=""
        />

        <h5 className="fw-bold my-2">Numero:</h5>
        <p>#{pokemon.id}</p>

        <h5 className="fw-bold mb-2">Tipo:</h5>
        <div>
          {pokemon.types.map((item, index) => (
            <span 
              key={index}
              className={`${styles.type} ${styles['type_' + item.type.name]}`}>
              {item.type.name}
            </span>
          ))}
        </div>

        <div className={styles.data_container}>
          <div className={styles.data_height}>
            <h4>Altura:</h4>
            <p>{pokemon.height * 10} cm</p>
          </div>
          <div className={styles.data_weight}>
            <h4>Peso:</h4>
            <p>{pokemon.weight / 10} kg</p>
          </div>
          
        </div>
        <Link href="/" className="btn btn-danger">Voltar</Link>
      </div>
    </div>
   </>
  )
}
